<?php
$block->redirectIfNotLoggedIn();
//echo "test";
//echo "<pre>";
$loginid = $block->getLoginId();
$customercollection = $block->getCustomerQuestions($loginid);
$customeranswers = $block->getCustomerAnswers($loginid);
?>
<h4>Your Questions</h4>
<div class="table-wrapper">
    <table class="data-table table" id="aw-pq-customer-questions-table">
        <col width="150" />
        <col />
        <col width="1" />
        <col width="130" />
        <thead>
            <tr>
                <th><span class="nobr">Product</span></th>
                <th><span class="nobr">Question</span></th>
                <th><span class="nobr">Answers</span></th>
                <th><span class="nobr">Status</span></th>
                <th><span class="nobr">Is Answered?</span></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($customercollection as $collection) {
                $faq_answers = $block->getAnswersCount($collection['faq_id']);
                $proname='';
                $prourl='';
                $proname = $block->getproname($collection['pro_id']);
                $prourl = $block->getprourl($collection['pro_id']);
                ?>
                <tr>
                    <td><a target="_Blank" href="<?= /* @noEscape */ $prourl?>" title="<?= /* @noEscape */ $proname?>"><?= /* @noEscape */ $proname?></a></td>
                    <td ><?= /* @noEscape */ $collection['title']; ?></td>
                    <td title="<?= /* @noEscape */ $collection['title']; ?>"><?= /* @noEscape */ count($faq_answers); ?></td>
                    <td><?php if ($collection['status']==0) { echo "Pending"; }else{ echo "Published";}?></td>
                    <td><span class="nobr"><?php if (count($faq_answers)==0) { echo "Not yet";
                                           } else { echo "Yes"; }?></span></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<h4>Your Answers</h4>
<div class="table-wrapper">
    <table class="data-table table" id="aw-pq-customer-answers-table">
        <col width="150" />
        <col width="220" />
        <col width="220"/>
        <col width="50" />
        <thead>
            <tr>
                <th><span class="nobr">Product</span></th>
                <th><span class="nobr">Question</span></th>
                <th><span class="nobr">Answer</span></th>
                <th><span class="nobr">Status</span></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($customeranswers as $collection) {
                $faq = $block->getFaq($collection['faq_id']);
                $proname='';
                $prourl='';
                $proname = $block->getproname($faq[0]['pro_id']);
                $prourl = $block->getprourl($faq[0]['pro_id']);
                ?>
                <tr>
                    <td><a target="_Blank" href="<?= /* @noEscape */ $prourl?>" title="<?= /* @noEscape */ $proname?>"><?= /* @noEscape */ $proname?></a></td>
                    <td title="<?= /* @noEscape */ $faq[0]['title']?> "><?= /* @noEscape */ $faq[0]['title']?></td>
                    <td title="<?= /* @noEscape */ $collection['answer']?> "><?= /* @noEscape */ $collection['answer']?></td>
                    <td><?php if ($collection['status']==0) {echo "Pending";} else {echo "Published";} ?></td>
                </tr>
            <?php  } ?>
        </tbody>
    </table>
</div>
