<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
$topicsData = $block->getCurrentTopicDetail();
$answerLengthAllowed = $block->allowedAnswerLength();
?>
<div class="faq_block" data-rating-role="rating-placeholder">
    <div id="rating-response"></div>
    <h2><?= /* @noEscape */ $topicsData->getTitle(); ?></h2>
    <?php if ($topicsData->getImage()): ?>
        <div class="banner">
            <img alt="" src="<?= /* @noEscape */ $block->getMediaDirectoryUrl().$topicsData->getImage()?>">
        </div>
    <?php endif; ?>
    <ul id="<?= /* @noEscape */ 'accordion_element' ?>" <?php if ($block->isAccordionEnable()):?>
    data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": true}}' <?php endif; ?>>
    <?php $faqsColection = $block->getDetailPageFaqs($topicsData->getId());
    if ($faqsColection->count() > 0):
        foreach ($faqsColection as $faq):
            ?>
            <li><div data-role="collapsible">
                <div class="accordion-toggle" data-role="trigger"><?= /* @noEscape */ $faq->getTitle(); ?></div></div>
                <div class="accordion-content" data-role="content">
                    <p>
                        <?php
                        $answer = /* @noEscape */ $faq->getFaqAnswer();
                        if ($answerLengthAllowed == 0 || (strlen($answer) <= $answerLengthAllowed)):
                            echo $answer;
                        else:
                            echo substr($answer, 0, $answerLengthAllowed).' <a title="'."View Detail".'" href="'.$block->getFaqUrl($faq).'">...</a>';
                        endif;
                        ?>
                    </p>
                    <?php if ($block->isRatingEnable()) { ?>
                        <div class="br-theme-css-stars">
                            <select id="<?= /* @noEscape */ $faq->getId(); ?>" data-stars-role="<?= /* @noEscape */ (int) $faq->getRatingStars(); ?>" data-customer-rate-readonly="<?= /* @noEscape */ $block->isCustomerReadonlyStars($faq->getId())?>">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>
                        </div>
                    <?php } ?>
                </div>
            </li>
        <?php endforeach; else: ?>
        <div class="message notice">
            <div>
                <?= /* @noEscape */ __('There are no faqs for this topic.');  ?>
            </div>
        </div>
        <?php endif; ?>
</ul>
</div>
<?php if ($block->isRatingEnable()) { ?>
    <script>
        require([
            'jquery',
            'barrating'
            ], function ($) {
            $('.br-theme-css-stars select').barrating({
                theme : 'css-stars',
                initialRating : true,
                onSelect : function(value, text, faq, event){
                    if(typeof(event) !== undefined){
                        $('#rating-response').text('');
                        $.ajax({
                            method: "POST",
                            dataType: "json",
                            url: "<?= /* @noEscape */ $block->getRatingAjaxUrl() ?>",
                            data: { value: value, faq: faq }
                        }).done(function( res ) {
                            if(res.error === false){
                                $('#rating-response').text(res.message);
                                if($('#rating-response').hasClass('rate-fail')){
                                    $('#rating-response').removeClass('rate-fail');
                                }
                                $('#rating-response').addClass('rate-success');
                                $('#'+faq).barrating('readonly', true);
                            }else{
                                $('#rating-response').text(res.message);
                                if($('#rating-response').hasClass('rate-success')){
                                    $('#rating-response').removeClass('rate-success');
                                }
                                $('#rating-response').addClass('rate-fail');
                            }
                        });
                    }
                }
            });
        });
    </script>
    <script type="text/x-magento-init">
        {
            "[data-rating-role=rating-placeholder]": {
                "I98commerce_Prodfaqs/js/barrating":
                {}
            }
        }
    </script>
<?php } ?>
