<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Adminhtml\Category\AssignProducts $block */

/** @var \Magento\Catalog\Block\Adminhtml\Category\Tab\Product $blockGrid */

$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();

?>
<?= /* @noEscape */ $block->getGridHtml(); ?>
<input type="hidden" name="category_products" id="in_category_products" data-form-part="faqs_index_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "I98commerce_Prodfaqs/faq/assign-products": {
                "selectedProducts": <?= /* @escapeNotVerified */ /* @noEscape */ $block->getProductsJson(); ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */  /* @noEscape */ '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
